services:
  gog:
    build: .
    image: lgogdownloader:latest
    volumes:
      - ./config:/config
      - e:\Games\GOG:/downloads
    environment:
      - XDG_CONFIG_HOME=/config
    entrypoint: lgogdownloader
